TOP = ..
include $(TOP)/configure/CONFIG
DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *IOC))
#DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard simDetectorIOC))
include $(TOP)/configure/RULES_DIRS

