#!/bin/bash

function parse_header() {

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
input="$SCRIPT_DIR/envPaths.linux"


while IFS=',' read -r f1 f2
do
f1=${f1#"epicsEnvSet("}
f1=${f1:1:-1}

f2=${f2%")"}
f2=${f2:1:-1}

#echo "$f1=$f2" 
f3="$f1=$f2" 

export $f3
#echo $f3

done < "$input"
}

function parse_medm_paths()
{

# must be first since User/beamlines override go here so that they get found first

if [ -n "$TOP" ];           then EDP=${TOP}/op/adl; fi

#actually defined Area Detectors or plugins are tested for here

if [ -n "$ADARAVIS" ];      then EDP=$EDP:${ADARAVIS}/aravisApp/op/adl; fi
if [ -n "$ADCORE" ];        then EDP=$EDP:${ADCORE}/ADApp/op/adl; fi
if [ -n "$ADGENICAM" ];     then EDP=$EDP:${ADGENICAM}/GenICamApp/op/adl; fi
if [ -n "$ADPIXIRAD" ];     then EDP=$EDP:${ADPIXIRAD}/pixiradApp/op/adl; fi
if [ -n "$ADPOINTGREY" ];   then EDP=$EDP:${ADPOINTGREY}/pointGreyApp/op/adl; fi
if [ -n "$ADPROSILICA" ];   then EDP=$EDP:${ADPROSILICA}/prosilicaApp/op/adl; fi
if [ -n "$ADSPINNAKER" ];   then EDP=$EDP:${ADSPINNAKER}/spinnakerApp/op/adl; fi
if [ -n "$ADSIMDETECTOR" ]; then EDP=$EDP:${ADSIMDETECTOR}/simDetectorApp/op/adl; fi
if [ -n "$ADURL" ];         then EDP=$EDP:${ADURL}/urlApp/op/adl; fi
if [ -n "$ADVIMBA" ];       then EDP=$EDP:${ADVIMBA}/vimbaApp/op/adl; fi

if [ -n "$ADMAR345" ];       then EDP=$EDP:${ADMAR345}/mar345App/op/adl; fi
if [ -n "$ADPILATUS" ];       then EDP=$EDP:${ADPILATUS}/ilatusApp/op/adl; fi
if [ -n "$ADEIGER" ];       then EDP=$EDP:${ADEIGER}/eigerApp/op/adl; fi

# commonly used synApps module screen are tested for here 

if [ -n "$ASYN" ];          then EDP=$EDP:${ASYN}/opi/medm; fi
if [ -n "$ALIVE" ];         then EDP=$EDP:${ALIVE}/aliveApp/op/adl; fi
if [ -n "$AUTOSAVE" ];      then EDP=$EDP:${AUTOSAVE}/asApp/op/adl; fi
if [ -n "$BUSY" ];          then EDP=$EDP:${BUSY}/busyApp/op/adl; fi
if [ -n "$CALC" ];          then EDP=$EDP:${CALC}/calcApp/op/adl; fi
if [ -n "$DEVIOCSTATS" ];   then EDP=$EDP:${DEVIOCSTATS}/op/adl; fi
if [ -n "$LUA" ];           then EDP=$EDP:${LUA}/luaApp/op/adl; fi
if [ -n "$SSCAN" ];         then EDP=$EDP:${SSCAN}/sscanApp/op/adl; fi
if [ -n "$XXX" ];           then EDP=$EDP:${XXX}/xxxApp/op/adl; fi


#Export 
f4="EPICS_DISPLAY_PATH=$EDP"

echo $f4
export $f4

}

function parse_caqtdm_paths()
{

# must be first since User/beamlines override go here so that they get found first

if [ -n "$TOP" ];           then EDP=${TOP}/op/:${ADCORE}/ADApp/op/ui/; fi

#actually defined Area Detectors or plugins are tested for here

if [ -n "$ADARAVIS" ];      then EDP=$EDP:${ADARAVIS}/aravisApp/op/ui/autoconvert; fi
if [ -n "$ADCORE" ];        then EDP=$EDP:${ADCORE}/ADApp/op/ui/autoconvert:${ADCORE}/ADApp/op/ui/; fi
if [ -n "$ADGENICAM" ];     then EDP=$EDP:${ADGENICAM}/GenICamApp/op/ui/autoconvert; fi

if [ -n "$ADPOINTGREY" ];   then EDP=$EDP:${ADPOINTGREY}/pointGreyApp/op/ui/autoconvert; fi
if [ -n "$ADPROSILICA" ];   then EDP=$EDP:${ADPROSILICA}/prosilicaApp/op/ui/autoconvert; fi
if [ -n "$ADSPINNAKER" ];   then EDP=$EDP:${ADSPINNAKER}/spinnakerApp/op/ui/autoconvert; fi
if [ -n "$ADSIMDETECTOR" ]; then EDP=$EDP:${ADSIMDETECTOR}/simDetectorApp/op/ui/autoconvert; fi
if [ -n "$ADURL" ];         then EDP=$EDP:${ADURL}/urlApp/op/ui/autoconvert; fi
if [ -n "$ADVIMBA" ];       then EDP=$EDP:${ADVIMBA}/vimbaApp/op/ui/autoconvert; fi
if [ -n "$ADPIXIRAD" ];     then EDP=$EDP:${ADPIXIRAD}/pixiradApp/op/ui/autoconvert; fi
if [ -n "$ADMAR345" ];      then EDP=$EDP:${ADMAR345}/mar345App/op/ui/autoconvert; fi
if [ -n "$ADPILATUS" ];     then EDP=$EDP:${ADPILATUS}/ilatusApp/op/ui/autoconvert; fi
if [ -n "$ADEIGER" ];       then EDP=$EDP:${ADEIGER}/eigerApp/op/ui/autoconvert; fi

# commonly used synApps module screen are tested for here 

if [ -n "$ASYN" ];          then EDP=$EDP:${ASYN}/opi/caqtdm/autoconvert; fi
if [ -n "$ALIVE" ];         then EDP=$EDP:${ALIVE}/aliveApp/ui/autoconvert; fi
if [ -n "$AUTOSAVE" ];      then EDP=$EDP:${AUTOSAVE}/asApp/op/ui/autoconvert; fi
if [ -n "$BUSY" ];          then EDP=$EDP:${BUSY}/busyApp/op/ui/autoconvert; fi
if [ -n "$CALC" ];          then EDP=$EDP:${CALC}/calcApp/ui/autoconvert; fi
if [ -n "$DEVIOCSTATS" ];   then EDP=$EDP:${DEVIOCSTATS}/op/ui/autoconvert; fi
if [ -n "$LUA" ];           then EDP=$EDP:${LUA}/luaApp/op/ui/autoconvert; fi
if [ -n "$SSCAN" ];         then EDP=$EDP:${SSCAN}/sscanApp/op/ui/autoconvert; fi
if [ -n "$XXX" ];           then EDP=$EDP:${XXX}/xxxApp/op/ui/autoconvert; fi


#Export 
f5="CAQTDM_DISPLAY_PATH=$EDP"

echo $f5
export $f5

}

function do_caqtdm ()
{
parse_header
parse_caqtdm_paths

/APSshare/caqtdm/caqtdm-4.2.0/caQtDM_Binaries/caQtDM -x -macro "P=xxx:, R=cam1:, C=$2" $1.ui &

#expensive !!!!!
#/APSshare/caqtdm/caqtdm-4.2.0/caQtDM_Binaries/caQtDM -attach -x -macro "P=xxx:, R=cam1:, C=$2" ad_cam_image.ui &

}

function do_medm ()
{
parse_header
parse_medm_paths

medm -x -macro "P=xxx:, R=cam1:, C=$2" $1.adl &

}

###########################################################################

#as required to supress dulipcate interface GUI messages
#export EPICS_CA_AUTO_ADDR_LIST=NO
#export EPICS_CA_ADDR_LIST=169.254.255.255

# start main Area Detector screen here . . . 

#export STARTUP=ADAravis
#export STARTUP=pixirad
#export STARTUP=pointGrey
#export STARTUP=prosilica
#export STARTUP=pixirad
#export STARTUP=ADSpinnaker
#export STARTUP=simDetector
#export STARTUP=URLDriver
#export STARTUP=ADVimba
#export STARTUP=mar345
#export STARTUP=pilatusDetector
#export STARTUP=eigerDetector
export STARTUP=xxx

export TYPE=
#export TYPE=FLIR-Oryx-ORX-10G-310S9M

#do_caqtdm $STARTUP $TYPE
do_medm $STARTUP $TYPE




